### PR TITLE
allow base 4.8

### PR DESCRIPTION
**Pull request by larskuhtz**

### CODE REVIEW

**Comment by jonsterling** [comment]
Hmm, looks like I haven't set up CI on this repo. I assume you've tried to build this with `4.8` with no trouble?

**Comment by larskuhtz** [comment]
Yes, building with `--allow-newer=base` worked fine. Haven't tested the code, though, but I don't expect any issue there.

**Comment by jonsterling** [comment]
OK, I'll just go ahead and merge it then.

**Comment by jonsterling** [comment]
thanks!

**Pull request merged**
